services:
  app:
    build: .
    ports:
      - "${SPRING_APP_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tareas-network

networks:
  tareas-network:
    driver: bridge

volumes:
  postgres_data: